KOBJECTS	=drivr.o
OBJECTS		=driver.o

INCLUDES=../include

.PHONY:all
all:
	$(CC) $(CFLAGS) -c -o drivr.o driver.c


.PHONY:clean
clean:
#	($(CD) $(MEN_DIR);$(MAKE) clean)
#	($(CD) $(SCHED_DIR);$(MAKE) clean)
	$(RM) -f *.o
